version: '3'

services:
  postgres-user:
    image: postgres
    container_name: postgres-user
    ports:
        - "5433:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1111
        - POSTGRES_DB=test_task

  user-service:
    build: ./
    container_name: user-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-user:5432/test_task
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
    depends_on:
      - postgres-user
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"