server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    name: postgres
    password: nickfury
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

SECRET_KEY: "ArtemSecret"

