server:
  port: 8084

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/test-task
    password: nickfury
    username: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/test-task
    user: postgres
    password: nickfury
    group: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

SECRET_KEY: "566D597133743677397A24432646294A404E635266556A576E5A723475377821"

management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  token:
    expiredTime: 3600000
  refresh:
    token:
      expiredTime:
        min: 720