CREATE TABLE refresh_tokens
(
    id bigint primary key generated by default as identity,
    token varchar not null unique,
    expired_at timestamp not null,
    user_id bigint not null references users(id)
);